sudo: required
services:
  - docker

before_install:
  - docker build -t adityarao/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run adityarao/react-test npm test -- --coverage

after_success:
  - docker build -t adityarao/multi-client ./client
  - docker build -t adityarao/multi-nginx ./nginx
  - docker build -t adityarao/multi-server ./server
  - docker build -t adityarao/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push into Docker Hub
  - docker push adityarao/multi-client
  - docker push adityarao/multi-nginx
  - docker push adityarao/multi-server
  - docker push adityarao/multi-worker


